_target_: model.probing.mlp.TenneyMLP

input_dim: ${model.pooler.hidden_dim}
hidden_dim: 256
output_dim: ${datamodule.dataset.num_classes}
dropout: 0.3
single_span: ${datamodule.dataset.task.single_span}