name: pl-template
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - pip=20.2.2
  - python=3.9
  - pytorch=1.9.0
  - torchvision
  - torchaudio
  - cudatoolkit=11.1
  - pytorch-lightning=1.3.8
  - wandb=0.12.1
  - scikit-learn=0.24.2
  - pip:
      - hydra-core==1.1.0