name: pl-template
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - pip=20.2.2
  - python=3.9
  - pytorch=1.9.0
  - torchvision
  - torchaudio
  - cudatoolkit=11.1
  - pytorch-lightning=1.5.7
  - scikit-learn=0.24.2
  - transformers=4.11.3
  - pip:
      - hydra-core==1.1.0
      - wandb==0.12.9