name: probing-search
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip=22.0.3
  - setuptools=59.5.0
  - spacy=2.1.8
  - pytorch=1.11.0
  - cudatoolkit=11.3
  - pytorch-lightning=1.5.10
  - torchmetrics=0.7.3
  - transformers=4.16.2
  - scikit-learn=1.0.2
  - h5py=3.3.0
  - pip:
      - hydra-core==1.1.0
      - wandb==0.12.12
