name: probing-search
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip=22.0.3
  - pytorch=1.9.0
  - torchvision
  - torchaudio
  - cudatoolkit=11.1
  - pytorch-lightning=1.5.7
  - torchmetrics=0.7.1
  - scikit-learn=0.24.2
  - transformers=4.11.3
  - spacy == 2.1.8
  - pip:
      - hydra-core==1.1.0
      - wandb==0.12.9
      - setuptools==59.5.0
