defaults:
  - task: double_span_score
  - preprocessor: bert
  - metrics/default_set@_here_

_target_: datamodule.dataset.JSONLDataset
name: msm_sem_sim

raw_file: data/msm/sem_sim/msmarco_sem_sim_60000_10_2022_03_21-17-06-14.json

train_file: data/msm/sem_sim/train.jsonl
val_file: data/msm/sem_sim/validation.jsonl
test_file: data/msm/sem_sim/test.jsonl

num_train_samples: 40000
num_test_samples: 20000

num_classes: 10