defaults:
  - task: single_span_class
  - preprocessor: bert_retokenization
  - metrics/default_set@_here_

_target_: datamodule.dataset.JSONLDataset
name: msm_ner

raw_file: data/msm/ner/msmarco_ner_60000_10_2022_01_14-16-41-48.json

train_file: data/msm/ner/train.jsonl
val_file: data/msm/ner/validation.jsonl
test_file: data/msm/ner/test.jsonl
label_file: data/msm/ner/labels.txt

num_train_samples: 40000
num_test_samples: 20000

num_classes: 18