_target_: model.probing.mlp.HewittMLP

input_dim: ${model.pooler.hidden_dim}
hidden_dim: 256
output_dim: ${datamodule.dataset.num_classes}
dropout: 0.0
pair_targets: ${datamodule.dataset.task.has_pair_targets}