_target_: model.probing.mlp.TenneyMLP

input_dim: ${model.pooler.hidden_dim}
hidden_dim: 512
output_dim: ${datamodule.dataset.num_classes}
dropout: 0.2
pair_targets: ${datamodule.dataset.task.has_pair_targets}