_target_: preprocessor.BERTPreprocessor
tokenizer_name: 'bert-base-uncased'
single_span: ${datamodule.dataset.task.single_span}
bucketize_labels: ${datamodule.dataset.task.regression_target}
num_buckets: ${datamodule.dataset.num_classes}