defaults:
  # sub-configs to include by default
  - model: probing_pair
  - datamodule: probing
  - loop: default_loop

gpus: 1
num_workers: 4
random_seed: 1590258941
continue_from_checkpoint: null

training:
  epochs: 30
  batch_size: 32
  gradient_clip_val: 5.0
  accumulate_batches: 1
  # checkpointing and early stopping
  save_ckpts: 1
  monitor: val/loss
  mode: min
  patience: 5

testing:
  log_dir: 'outputs/'
  test_best_k: 5
  batch_size: 32

metrics:
  to_probabilities: 'sigmoid'
  metrics_list:
    - _target_: torchmetrics.F1
      average: 'micro'

log_gradients: False
logger: # set to null to use PL default logging
  _target_: logger.loggers.WandbMinMaxLogger
  project: probing-search

tags:
  - 'layer:${model.pooler.layer_to_probe}'
  - ${datamodule.dataset.name}

# set output directories
hydra:
  run:
    dir: outputs/single/${datamodule.dataset.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}

  sweep:
    dir: outputs/sweep/${datamodule.dataset.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: 'layer=${model.pooler.layer_to_probe}'
  # ${hydra.job.num}

