defaults:
  - model: probing_pair
  - datamodule: probing
  #  - datamodule/preprocessor: ${model/subject_model}
  - loop: default_loop

gpus: 1
num_workers: 4
random_seed: 1590258941

training:
  epochs: 100
  batch_size: 32
  accumulate_batches: 1
  # checkpointing
  save_ckpts: 10
  monitor: val_loss
  mode: min
  patience: 5

testing:
  log_dir: 'outputs/'
  test_best_k: 5
  batch_size: 512

metrics:
  - _target_: torchmetrics.Accuracy
  - _target_: torchmetrics.F1
    num_classes: 10

logger:
  _target_: logger.loggers.WandbMinMaxLogger
log_gradients: False

hydra:
  run:
    dir: outputs/${datamodule.dataset.name}/${model.subject_model._target_}/${now:%Y-%m-%d}/${now:%H-%M-%S}