_target_: model.subject.bert.BERTBaseFromLocalCheckpoint
ckpt_path: ${hydra:runtime.cwd}/data/model_checkpoints/bert/bert_msm_passage.ckpt
model_name: bert-msm-passage
num_layers: ${model.pooler.layer_to_probe}